### ISSUE TITLE
Sektion für Source Code Management fehlt

### ISSUE THREAD

**Issue by meisterluk** [linuxtage/commands-cheatsheet#1]
SCM würde git und optional Subversion beinhalten. Ich denke Mercurial und Bazaar sind zu unbekannt.

Im ersten Release wurde es aus Platzgründen nicht inkludiert.

**Comment by flowolf** [comment]
git ist vlt Overkill, muss nicht rein IMHO. Vor allem auch weil wenig Platz ist und die Basiskommandos schon etwa 10 Zeilen brauchen...
wir könnten aber einen GIT-Spickzettel auflegen ;)
