### ISSUE TITLE
Pipe fehlt in Sektion "Weiterleitung"

### ISSUE THREAD

**Issue by meisterluk** [linuxtage/commands-cheatsheet#11]
Laut Feedback von MacLemon abgeleitet von

> @meisterluk Dann ist da zu viel drauf. :-) Bissl Feedback (Nein, ich compile mir jetzt keinen Scribus) https://maclemon.at/downloads/cheatsheet-sw_MacLemon_Feedback.pdf

Das PDF notiert `missing: cmd1 | cmd2`.

**Comment by meisterluk** [comment]
Pipes als Begriff ist unbrauchbar für Anfänger (Experten ist die Basisnotation klar). Filter wäre brauchbar, aber ist ungewohnt. Daher wäre eine differenzierte Beschreibung notwendig. Hierfür fehlt der Platz. Weiters wäre es notwendig diese in Kombination mit den Redirects zu setzen.

**Comment by flowolf** [comment]
`grep XY file | gzip - > fileXY.gz` ... Inhalte die auf XY matchen (aus file an gzip weiterleiten und) komprimiert in fileXY.gz speichern

**Comment by meisterluk** [comment]
`grep | zip` war zu lang. Aber eine allgemeine Beschreibung ist jetzt inkludiert.
