### ISSUE TITLE
"man [section] keyword" mit Sektionen auflisten anstatt jeder man section

### ISSUE THREAD

**Issue by meisterluk** [linuxtage/commands-cheatsheet#12]
Laut Feedback von MacLemon abgeleitet von

> @meisterluk Dann ist da zu viel drauf. :-) Bissl Feedback (Nein, ich compile mir jetzt keinen Scribus) https://maclemon.at/downloads/cheatsheet-sw_MacLemon_Feedback.pdf

Es wäre sinnvoller

```
man [section] file
1 … general commands
2 … System calls
3 … …
```

aufzulisten als

```
man 1 <cmd> General commands
man 2 <syscall> System calls
```

wobei beim 2. Ansatz nicht alle Sektionen ausgewiesen werden können.

**Comment by rubienr** [comment]
Personally I would also add a hint to `whatis name`, which helped me a lot as beginner and still does a good job as advanced user. I find the output being more intuitive and readable than `apropos`'s output.

**Comment by meisterluk** [comment]
Thanks for the feedback, @rubienr !

**Comment by meisterluk** [comment]
`whatis` is now included in Release 2.0. I think all feedback was addressed. Please open, if you think otherwise.
